from django.db import models

# Create your models here.
class User(models.Model):
    openid = models.TextField()
    userType = models.TextField(default='普通用户')
    vipid = models.TextField(null=True)


    class Meta:
        db_table = 'user'

class food_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'food_goods'

class nofood_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'nofood_goods'

class fresh_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'fresh_goods'

class out_window_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'out_window_goods'

class fruit_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'fruit_goods'

class vegetable_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'vegetable_goods'

class dry_fruit_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'dry_fruit_goods'

class meat_goods(models.Model):
    bar_code = models.TextField(null=True)
    coding = models.TextField(null=True)
    maingoods_coding = models.TextField(null=True)
    goodsname = models.TextField(null=True)
    unit = models.TextField(null=True)
    package = models.TextField(null=True)
    goodsType = models.TextField(null=True)
    goods_classify_code = models.TextField(null=True)
    supplier = models.TextField(null=True)
    expiration_date = models.TextField(null=True)
    origin = models.TextField(null=True)
    count_type = models.TextField(null=True)
    goodsStatus = models.TextField(null=True)
    cost = models.TextField(null=True)
    retail_price = models.TextField(null=True)
    vip_price = models.TextField(null=True)
    send_price = models.TextField(null=True)
    trade_price = models.TextField(null=True)
    minimum_stock = models.TextField(null=True)
    highest_stock = models.TextField(null=True)
    initial_amount = models.TextField(null=True)
    initial_count = models.TextField(null=True)
    replenishment_logo = models.TextField(null=True)
    replenishment_period = models.TextField(null=True)
    minimum_replenishment_volume = models.TextField(null=True)
    standard = models.TextField(null=True)
    goodsMode = models.TextField(null=True)
    brand = models.TextField(null=True)
    remark = models.TextField(null=True)
    goods_img = models.ImageField(upload_to='goods_img',null=True)
    goods_desc = models.TextField(null=True)
    goods_detail_img1 = models.ImageField(upload_to='goods_detail_img1',null=True)
    goods_detail_img2 = models.ImageField(upload_to='goods_detail_img2', null=True)

    class Meta:
        db_table = 'meat_goods'


class Market(models.Model):
    userid = models.TextField()
    goodsid = models.TextField()
    buycount = models.TextField()
    isselect = models.TextField()

    class Meta:
        db_table = 'market'