# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-16 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bean_goods',
        ),
        migrations.DeleteModel(
            name='cereals_goods',
        ),
        migrations.DeleteModel(
            name='dry_crigo_goods',
        ),
        migrations.DeleteModel(
            name='frozen_balls_goods',
        ),
        migrations.DeleteModel(
            name='scattered_said_goods',
        ),
    ]
