# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-16 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0002_auto_20190116_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('goodsid', models.TextField()),
                ('buycount', models.TextField()),
                ('isselect', models.TextField()),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
