# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0005_auto_20190117_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='pintuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.TextField()),
                ('userid', models.TextField()),
                ('pintuan_code', models.TextField()),
                ('pt_people', models.TextField()),
                ('pt_start_time', models.DateTimeField(auto_now_add=True)),
                ('pt_end_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pintuan',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
