# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0006_auto_20190117_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viptime', models.TextField()),
                ('price', models.TextField()),
                ('days', models.TextField()),
            ],
            options={
                'db_table': 'vip',
            },
        ),
    ]
