# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0007_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='viptype',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
