# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0008_vip_viptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.TextField(default='普通会员'),
        ),
    ]
