# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0009_auto_20190117_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='morning_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.TextField()),
                ('unit', models.TextField()),
                ('goodtype', models.TextField()),
                ('promotion_price', models.TextField()),
                ('price', models.TextField()),
                ('standard', models.TextField()),
                ('pt_start_time', models.DateTimeField(auto_now_add=True)),
                ('pt_end_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'morning_market',
            },
        ),
        migrations.CreateModel(
            name='pt_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.TextField()),
                ('unit', models.TextField()),
                ('goodtype', models.TextField()),
                ('pt_price', models.TextField()),
                ('price', models.TextField()),
                ('standard', models.TextField()),
                ('pt_start_time', models.DateTimeField(auto_now_add=True)),
                ('pt_end_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pt_people', models.TextField()),
            ],
            options={
                'db_table': 'pt_good',
            },
        ),
        migrations.RemoveField(
            model_name='pintuan',
            name='pt_end_time',
        ),
        migrations.RemoveField(
            model_name='pintuan',
            name='pt_people',
        ),
        migrations.RemoveField(
            model_name='pintuan',
            name='pt_start_time',
        ),
        migrations.RemoveField(
            model_name='pintuan',
            name='update_time',
        ),
    ]
