# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0010_auto_20190117_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dry_fruit_goods',
        ),
        migrations.DeleteModel(
            name='fresh_goods',
        ),
        migrations.DeleteModel(
            name='fruit_goods',
        ),
        migrations.DeleteModel(
            name='meat_goods',
        ),
        migrations.DeleteModel(
            name='nofood_goods',
        ),
        migrations.DeleteModel(
            name='out_window_goods',
        ),
        migrations.DeleteModel(
            name='vegetable_goods',
        ),
        migrations.AddField(
            model_name='food_goods',
            name='goodsTypes',
            field=models.TextField(null=True),
        ),
    ]
