# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0013_auto_20190117_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_goods_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=128)),
                ('goodsid', models.TextField()),
                ('userid', models.TextField()),
                ('goods_num', models.TextField()),
                ('goodsprice', models.TextField()),
                ('status', models.TextField()),
                ('create_time', models.TextField()),
                ('update_time', models.TextField()),
                ('pay_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=128)),
                ('userid', models.TextField()),
                ('pay_price', models.TextField()),
                ('is_pay', models.TextField()),
                ('pay_time', models.DateTimeField()),
                ('is_ship', models.TextField()),
                ('ship_time', models.DateTimeField()),
                ('is_receipt', models.TextField()),
                ('receipt_time', models.TextField()),
                ('status', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_list',
            },
        ),
    ]
