# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0014_order_goods_list_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_morning',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
