# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0015_market_is_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='goodsname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
