# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-17 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0016_market_goodsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='goodsname',
            new_name='goodstype',
        ),
    ]
