# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0017_auto_20190117_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_goods_list',
            old_name='status',
            new_name='pay_status',
        ),
        migrations.AddField(
            model_name='order_goods_list',
            name='send_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_goods_list',
            name='pay_time',
            field=models.TextField(null=True),
        ),
    ]
