# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsx', '0022_order_goods_list_goodstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_goods_list',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_goods_list',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
